trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: SpokeNAT

stages:
- template: pipeline-templates/valandplan.yaml
- template: pipeline-templates/approval.yaml
- template: pipeline-templates/apply.yaml
